### ISSUE TITLE
Qwiic_IR_Array_MLX90640 not found by neither i2cdetect nor i2c mulitscanner

### ISSUE THREAD

**Issue by namoaton** [sparkfun/Qwiic_IR_Array_MLX90640#1]
### Subject of the issue
Qwiic_IR_Array_MLX90640 not found by neither i2cdetect nor i2c mulitscanner
There is a situation when connect scl line on logic analyzer not signal and low level

### Your workbench
* What platform are you using?
raspberry pi 3, linux, and i2 scanner on arduino.
* What version of the device are you using? Is there a firmware version?
last version, which produced in october. wait it for 2 month and now have such problem
* How is the device wired to your platform?
with qwiic connector and directly to pins on rpi3
* How is everything being powered?
from 3.3v pin on rpi3
* Are there any additional details that may help us help you?
I try as with pull up resistors and without them
### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.
In raspi-config enable i2c support. connect. try to run 'sudo i2cdetect -y 1' and nothing happens.

### Expected behaviour
Tell us what should happen
I expected to get found address 0x33 as described in  manual on Sparkfun site
### Actual behaviour
Tell us what happens instead
Nothing happens. I2cscanner freezes, logic anaylizer is silent, on rpi  silence.

**Comment by AndyEngland521** [comment]
This is a small hardware issue that we currently have a fix on order for. The bottom plate of the MLX is ground and on occasion, Solder will flow onto this plate, connecting a signal to ground. My guess is that this is what happened on your SCL signal, and it slipped through our quality control. We have fixed our design to remedy this issue, but it will take a bit of time for this new design to arrive, but give our customer service a call at 1-303-284-0979
