### ISSUE TITLE
Reading frames twice?

### ISSUE THREAD

**Issue by mranostay** [sparkfun/Qwiic_IR_Array_MLX90640#2]
https://github.com/sparkfun/Qwiic_IR_Array_MLX90640/blob/952cd5422d8e3c017954564c77adeaee9a776737/Firmware/Example1_BasicReadings/Example1_BasicReadings.ino#L73

So looking at this it seems you are reading the entire frame (both subpages) twice, but really only mean to do it once. Am I misreading that?

**Comment by mranostay** [comment]
Ah I see it is to get both subframes Ta constants

**Comment by nseidle** [comment]
Yep. Thanks for coming back and closing. Let me know if you see anything else that needs attention.
