### ISSUE TITLE
"MLX90640 not detected at default I2C address. Please check wiring. Freezing."

### ISSUE THREAD

**Issue by ManiLowc** [sparkfun/Qwiic_IR_Array_MLX90640#3]
### Subject of the issue
I've downloaded the example code and have been trying to get my sparkfun Qwiic IR Array MLX90640 to work but receive the above error. I have tried the i2c_scanner code to see if my Due was finding the array and it says that an I2C device was found. 

When I run the i2c_scanner code my serial port gives:
Scanning...
I2C device found at address 0x0A  !
I2C device found at address 0x13  !
I2C device found at address 0x1A  !
I2C device found at address 0x22  !
I2C device found at address 0x28  !
I2C device found at address 0x2E  !
I2C device found at address 0x34  !
I2C device found at address 0x3A  !
I2C device found at address 0x40  !
I2C device found at address 0x44  !
I2C device found at address 0x48  !
I2C device found at address 0x4C  !
I2C device found at address 0x50  !
I2C device found at address 0x54  !
I2C device found at address 0x57  !
I2C device found at address 0x5B  !
I2C device found at address 0x5F  !
I2C device found at address 0x62  !
I2C device found at address 0x66  !
I2C device found at address 0x6A  !
I2C device found at address 0x6D  !
I2C device found at address 0x71  !
I2C device found at address 0x74  !
I2C device found at address 0x78  !
I2C device found at address 0x7C  !
done

### Your workbench
* What platform are you using?
I'm using the Arduino Due, Qwiic Shield (DEV-14352 ) and Qwiic IR Array MLX90640 (55x35).
* What version of the device are you using? Is there a firmware version?
I'm using the latest Arduino Due, purchased in November 2018. My 'boards manager' and 'library manager' are all up to date with the latest versions. 
* How is the device wired to your platform?
I have connected the IR Array with a connector cable to the Qwiic Shield, which is pinned into the Arduino Due. I have the Shield connected to the Due such that A5, IRF, SCL, and RX on the board matches with the Arduino (SCL1 for the arduino) [I've tried attaching a picture as well to make it clearer]

* How is everything being powered?
I have connected the arduino to my pc to be powered. 
* Are there any additional details that may help us help you?
I'm a complete novice so sorry for any useless information. 

### Steps to reproduce
Tell us how to reproduce this issue. Please post stripped down example code demonstrating your issue to a gist.
I used the code on github, but for the first example I get the error of MLX not detected at default I2C address. 

### Expected behaviour
Tell us what should happen
I was expecting the code to run and see values on the serial monitor. 

### Actual behaviour
Tell us what happens instead
I get the error MLX90640 not detected at default I2C address. 
![20190217_173310](https://user-images.githubusercontent.com/47695821/52916719-f9fede80-32da-11e9-9020-e3d5d36486d2.jpg)

Thank you in advance for any help and it is greatly appreciated!

**Comment by nseidle** [comment]
Hi ManiLowc,

I recommend against using a Due. It's I2C implementation has been giving us problems with the ML90640. See this [issue](https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example/issues/1).

Second possible source of problems: We've had two revisions of this product. If you have the first revision, you may be running into a hardware issue. Can you please post a picture of your MLX90640?

For reference, on the 2nd rev of the board the tab on the sensor has been re-aligned to better line up the pixels of the frame to the orthagonal orientation of the board.

This is what rev one looks like:

![image](https://user-images.githubusercontent.com/117102/52969269-f9168d00-336c-11e9-8025-1818fc8fd3cb.png)

**Comment by ManiLowc** [comment]
Hi nseidle, 
Thank you for your quick reply. Please find attached a picture of my MLX90640.

For my project, I need a microcontroller with enough computing power that it can use the MLX90640 and encode the thermal data into a language of different frequencies to then be sent to an array of actuators. Would a teensy be best as it would work with the example code? May I ask what microcontroller you would recommend to a novice to use for this project? 
Many thanks.
![20190219_144101](https://user-images.githubusercontent.com/47695821/53024007-29862600-3456-11e9-9c1b-2b11f060cc32.jpg)

**Comment by nseidle** [comment]
That is indeed rev one and may be a hardware issue. It's going to be hard to trouble shoot via github. Please contact support@sparkfun.com and they'll get you squared away.
